### ISSUE TITLE
Installing on Debian

### ISSUE THREAD

**Issue by azureknight63** [TAAPArthur/TAAPCrunchyrollBot#1]
Forgive me if this is a stupid question, but how do I install on Debian? There is no ./configure and no instructions in the README for initial setup. Thank you!

**Comment by TAAPArthur** [comment]
The entire project is just a python script with a bash wrapper. Place `taapcrunchyroll-bot` in /usr/bin and place the python files in /usr/lib/taapcrunchyroll-bot/

After installing you'll need to configure $HOME/.config/taapcrunchyroll-bot/taapcrunchyroll-bot.conf. I'll update the readmore to include more details how what the variables mean.

Feel free to let me know if you have any questions/concerns/suggestions

**Comment by azureknight63** [comment]
Thank you for your response. I did as you said and it seems I may be missing some dependencies or something. I should also mention that I made a slight change to the Python file; instead of sys.argv[1]   and sys.argv[2] for user/pass, I put some strings into variables (my own user/pass) and used those, so the line numbers are a bit off in a few places. Here is the bash output:

> numberOfGroups '1'
getCredentialsScript '0'
updateUserInfoScript '0'
errorScript '0'
killTime '43200'
/usr/bin/taapcrunchyroll-bot: line 37: 0: command not found
Obtaining guest pass for  of Group 1
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/phantomjs/webdriver.py:49: UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
  warnings.warn('Selenium support for PhantomJS has been deprecated, please use headless '
/usr/lib/taapcrunchyroll-bot/crunchyrollGuestPassFinder.py
43200
2018/05/15 15:21:23: starting bot
2018/05/15 15:21:23: attempting to login to obfuscated@domain.com
Traceback (most recent call last):
  File "/usr/lib/taapcrunchyroll-bot/crunchyrollGuestPassFinder.py", line 174, in <module>
    crunchyrollGuestPassFinder=CrunchyrollGuestPassFinder(user, passwd)
  File "/usr/lib/taapcrunchyroll-bot/crunchyrollGuestPassFinder.py", line 35, in __init__
    self.login()
  File "/usr/lib/taapcrunchyroll-bot/crunchyrollGuestPassFinder.py", line 46, in login
    self.driver.find_element_by_id("login_form_name").send_keys(self.username)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 353, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 957, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 208, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: Error - Unable to load Atom 'find_element' from file ':/ghostdriver/./third_party/webdriver-atoms/find_element.js'
pyhton exited with error code 1
