### ISSUE TITLE
unknow json format files

### ISSUE THREAD

**Issue by Arthoruis** [TAAPArthur/TAAPCrunchyrollBot#2]
hi, what's the correct json file format. I am trying this: 

- username, password
- Username:username, Password:password

**Comment by TAAPArthur** [comment]
Try `{
"$USERNAME":  "$PASSWORD"
}`
Where $USERNAME and $PASSWORD are your account credentials. 

Or you could try with the `--save` or `-s` options which will prompt you for credentials and automatically save them

**Comment by Arthoruis** [comment]
It's worked, thanks a lot and nice work friend!! :)
